### ISSUE TITLE
unsolved training explosion

### ISSUE THREAD

**Issue by darongliu** [shawntan/neural-turing-machines#14]
I straightly running the code will lead to the score vibration around 5 or 4. So, I change the updating strategy to rmsprop, though the score will decrease to around 0.18 , it always explode at 11180 around. No matter how i adjust the clip bound or learning rate, it always goes that way. Is there anybody have the same issue?

**Comment by shawntan** [comment]
The score has always been unstable for me.

I'm working on a batched version of this, and moving to doing operations in log-space, and this seems to help. I'll rebase the changes to master once I have it properly working, it's still running into nan problems.
