### ISSUE TITLE
Completion

### ISSUE THREAD

**Issue by avinayak** [shawntan/neural-turing-machines#4]
Will you complete the program with sorting anytime?

**Comment by shawntan** [comment]
Ha, work's been kinda heavy the last couple of months.

I'm doubtful I can get that to work though. Even with the simplest task I couldn't get the network to converge. I'll work on it when I have more time.

You're welcome to try though, and please make a pull request!

**Comment by avinayak** [comment]
I'm having lots of free time! .I'll do my best to complete it.Thank You :smile:

**Comment by shawntan** [comment]
Lemme know if you need any help!
